"""add_competition_player_unique

Revision ID: d7f1a7df0fa2
Revises: e197c426a816
Create Date: 2026-07-01 22:49:47.277364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7f1a7df0fa2'
down_revision: Union[str, Sequence[str], None] = 'e197c426a816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_competition_player', 'competition_players', ['competition_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_competition_player', 'competition_players', type_='unique')
    # ### end Alembic commands ###
