"""make_club_id_nullable

Revision ID: f8a3b2c1d456
Revises: d7f1a7df0fa2
Create Date: 2026-07-02 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a3b2c1d456'
down_revision: Union[str, Sequence[str], None] = 'd7f1a7df0fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Make club_id nullable to support lobby competitions."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitions', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Restore club_id as non-nullable."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitions', 'club_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
